server:
  port: 3000
#  servlet:
#    context-path: /api

spring:
  datasource:
    username: root
    password: BJTU2023
    url: jdbc:mysql://8.130.141.182:3306/info?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  #redis:
    #port: 6379
    #host: 8.130.141.182
